In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../datasets/carrot_weight_dataset.csv")
df.head()

height  width  orange  purple  yellow  weight
0     151     36       0       1       0      71
1     192     26       0       0       1      95
2     114     31       0       1       0      72
3     171     36       1       0       0      86
4     160     32       1       0       0      83

In [3]:
df.shape

(1000, 6)

In [4]:
df.describe()

height        width       orange       purple       yellow  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean    149.937000    29.740000     0.514000     0.501000     0.240000   
std      29.990072     6.007036     0.500054     0.500249     0.427297   
min     100.000000    20.000000     0.000000     0.000000     0.000000   
25%     123.000000    24.750000     0.000000     0.000000     0.000000   
50%     150.000000    30.000000     1.000000     1.000000     0.000000   
75%     176.000000    35.000000     1.000000     1.000000     0.000000   
max     200.000000    40.000000     1.000000     1.000000     1.000000   

            weight  
count  1000.000000  
mean     78.653000  
std      13.738316  
min      45.000000  
25%      68.000000  
50%      79.000000  
75%      89.000000  
max     114.000000

In [5]:
df.isnull().sum()

height    0
width     0
orange    0
purple    0
yellow    0
weight    0
dtype: int64

In [6]:
df.dtypes

height    int64
width     int64
orange    int64
purple    int64
yellow    int64
weight    int64
dtype: object

In [7]:
df.drop(["yellow"], axis="columns", inplace=True)
df.head()

height  width  orange  purple  weight
0     151     36       0       1      71
1     192     26       0       0      95
2     114     31       0       1      72
3     171     36       1       0      86
4     160     32       1       0      83

In [8]:
X = df.drop(["weight"], axis="columns")
y = df["weight"]

In [9]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X[["height", "width"]] = scaler.fit_transform(df[["height", "width"]])
X.head()
# X[(X["red"]==0) & (X["green"]==0)]

height  width  orange  purple
0    0.51   0.80       0       1
1    0.92   0.30       0       0
2    0.14   0.55       0       1
3    0.71   0.80       1       0
4    0.60   0.60       1       0

In [10]:
scaler.data_min_     # array: [min_height, min_width]

array([100.,  20.])

In [11]:
scaler.data_max_ - scaler.data_min_  # range for scaling

array([100.,  20.])

In [12]:
min_vals = scaler.data_min_     # array: [min_height, min_width]
min_vals

array([100.,  20.])

In [13]:
scale_vals = scaler.data_max_ - scaler.data_min_  # range for scaling
scale_vals

array([100.,  20.])

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

# SVR

In [15]:
from sklearn.svm import SVR
model = SVR(kernel='linear', C=20, gamma='scale', epsilon=0.1, degree=0)
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.8459071050496176

In [16]:
import joblib
joblib.dump(model,"../Trained_model/Weights_Prediction_Carrot")

['../Trained_model/Weights_Prediction_Carrot']