In [35]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [36]:
df = pd.read_csv("../datasets/apple_weight_dataset.csv")
df.head()

height  width  red  green  red_and_green  weight
0     190    194    1      0              0     106
1     113    119    1      0              0     112
2     116    116    1      0              0     113
3     110    120    1      0              0     118
4     123    120    1      0              0     118

In [37]:
df.shape

(13, 6)

In [38]:
df.describe()

height       width   red  green  red_and_green      weight
count   13.000000   13.000000  13.0   13.0           13.0   13.000000
mean   140.923077  136.615385   1.0    0.0            0.0  128.846154
std     33.252723   28.306473   0.0    0.0            0.0   19.121742
min    110.000000  114.000000   1.0    0.0            0.0  106.000000
25%    123.000000  120.000000   1.0    0.0            0.0  113.000000
50%    126.000000  122.000000   1.0    0.0            0.0  118.000000
75%    140.000000  140.000000   1.0    0.0            0.0  145.000000
max    210.000000  194.000000   1.0    0.0            0.0  157.000000

In [39]:
df.isnull().sum()

height           0
width            0
red              0
green            0
red_and_green    0
weight           0
dtype: int64

In [40]:
df.dtypes

height           int64
width            int64
red              int64
green            int64
red_and_green    int64
weight           int64
dtype: object

In [41]:
df.drop(["red_and_green"], axis="columns", inplace=True)
df.head()

height  width  red  green  weight
0     190    194    1      0     106
1     113    119    1      0     112
2     116    116    1      0     113
3     110    120    1      0     118
4     123    120    1      0     118

In [42]:
X = df.drop(["weight"], axis="columns")
y = df["weight"]

In [43]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X[["height", "width"]] = scaler.fit_transform(df[["height", "width"]])
X.head()
# X[(X["red"]==0) & (X["green"]==0)]

height   width  red  green
0    0.80  1.0000    1      0
1    0.03  0.0625    1      0
2    0.06  0.0250    1      0
3    0.00  0.0750    1      0
4    0.13  0.0750    1      0

In [44]:
scaler.data_min_     # array: [min_height, min_width]

array([110., 114.])

In [45]:
scaler.data_max_ - scaler.data_min_  # range for scaling

array([100.,  80.])

In [46]:
min_vals = scaler.data_min_     # array: [min_height, min_width]
min_vals

array([110., 114.])

In [47]:
scale_vals = scaler.data_max_ - scaler.data_min_  # range for scaling
scale_vals

array([100.,  80.])

In [48]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

# SVR

In [49]:
from sklearn.svm import SVR
model = SVR(kernel='linear', C=20, gamma='scale', epsilon=0.1, degree=0)
model.fit(X_train, y_train)
model.score(X_test, y_test)

-1.4827272203794903

In [50]:
import joblib
joblib.dump(model,"../Trained_model/Weights_Prediction_Apple")

['../Trained_model/Weights_Prediction_Apple']