In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../datasets/orange_weight_dataset.csv")
df.head()

height  width  orange  green  orange_and_green  weight
0     205    191       1      0                 0     130
1     219    199       1      0                 0     147
2     229    198       1      0                 0     142
3     205    191       1      0                 0     130
4     219    199       1      0                 0     147

In [3]:
df.shape

(19, 6)

In [4]:
df.describe()

height       width  orange  green  orange_and_green      weight
count   19.000000   19.000000    19.0   19.0              19.0   19.000000
mean   161.473684  156.000000     1.0    0.0               0.0  163.842105
std     40.087915   28.284271     0.0    0.0               0.0   19.267887
min    119.000000  130.000000     1.0    0.0               0.0  130.000000
25%    134.500000  137.000000     1.0    0.0               0.0  147.000000
50%    141.000000  140.000000     1.0    0.0               0.0  166.000000
75%    205.000000  191.000000     1.0    0.0               0.0  179.500000
max    229.000000  199.000000     1.0    0.0               0.0  191.000000

In [5]:
df.isnull().sum()

height              0
width               0
orange              0
green               0
orange_and_green    0
weight              0
dtype: int64

In [6]:
df.dtypes

height              int64
width               int64
orange              int64
green               int64
orange_and_green    int64
weight              int64
dtype: object

In [7]:
df.drop(["orange_and_green"], axis="columns", inplace=True)
df.head()

height  width  orange  green  weight
0     205    191       1      0     130
1     219    199       1      0     147
2     229    198       1      0     142
3     205    191       1      0     130
4     219    199       1      0     147

In [8]:
X = df.drop(["weight"], axis="columns")
y = df["weight"]

In [9]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X[["height", "width"]] = scaler.fit_transform(df[["height", "width"]])
X.head()
# X[(X["red"]==0) & (X["green"]==0)]

height     width  orange  green
0  0.781818  0.884058       1      0
1  0.909091  1.000000       1      0
2  1.000000  0.985507       1      0
3  0.781818  0.884058       1      0
4  0.909091  1.000000       1      0

In [10]:
scaler.data_min_     # array: [min_height, min_width]

array([119., 130.])

In [11]:
scaler.data_max_ - scaler.data_min_  # range for scaling

array([110.,  69.])

In [12]:
min_vals = scaler.data_min_     # array: [min_height, min_width]
min_vals

array([119., 130.])

In [13]:
scale_vals = scaler.data_max_ - scaler.data_min_  # range for scaling
scale_vals

array([110.,  69.])

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

# SVR

In [15]:
from sklearn.svm import SVR
model = SVR(kernel='linear', C=20, gamma='scale', epsilon=0.1, degree=0)
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.6028049848061767

In [16]:
import joblib
joblib.dump(model,"../Trained_model/Weights_Prediction_Orange")

['../Trained_model/Weights_Prediction_Orange']