In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv("../datasets/banana_weight_dataset.csv")
df.head()

height  width  yellow  green  yellow_and_green  weight
0     107    335       1      0                 0     151
1     124    314       1      0                 0     161
2     104    322       1      0                 0     152
3     111    333       1      0                 0     161
4     143    346       1      0                 0     151

In [10]:
df.shape

(6, 6)

In [11]:
df.describe()

height       width  yellow  green  yellow_and_green      weight
count    6.000000    6.000000     6.0    6.0               6.0    6.000000
mean   116.833333  329.333333     1.0    0.0               0.0  154.000000
std     14.524692   11.165423     0.0    0.0               0.0    5.585696
min    104.000000  314.000000     1.0    0.0               0.0  148.000000
25%    108.000000  323.000000     1.0    0.0               0.0  151.000000
50%    111.500000  329.500000     1.0    0.0               0.0  151.500000
75%    121.000000  334.500000     1.0    0.0               0.0  158.750000
max    143.000000  346.000000     1.0    0.0               0.0  161.000000

In [12]:
df.isnull().sum()

height              0
width               0
yellow              0
green               0
yellow_and_green    0
weight              0
dtype: int64

In [13]:
df.dtypes

height              int64
width               int64
yellow              int64
green               int64
yellow_and_green    int64
weight              int64
dtype: object

In [14]:
df.drop(["yellow_and_green"], axis="columns", inplace=True)
df.head()

height  width  yellow  green  weight
0     107    335       1      0     151
1     124    314       1      0     161
2     104    322       1      0     152
3     111    333       1      0     161
4     143    346       1      0     151

In [15]:
X = df.drop(["weight"], axis="columns")
y = df["weight"]

In [16]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X[["height", "width"]] = scaler.fit_transform(df[["height", "width"]])
X.head()
# X[(X["red"]==0) & (X["green"]==0)]

height    width  yellow  green
0  0.076923  0.65625       1      0
1  0.512821  0.00000       1      0
2  0.000000  0.25000       1      0
3  0.179487  0.59375       1      0
4  1.000000  1.00000       1      0

In [17]:
scaler.data_min_     # array: [min_height, min_width]

array([104., 314.])

In [18]:
scaler.data_max_ - scaler.data_min_  # range for scaling

array([39., 32.])

In [19]:
min_vals = scaler.data_min_     # array: [min_height, min_width]
min_vals

array([104., 314.])

In [20]:
scale_vals = scaler.data_max_ - scaler.data_min_  # range for scaling
scale_vals

array([39., 32.])

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

# SVR

In [22]:
from sklearn.svm import SVR
model = SVR(kernel='linear', C=20, gamma='scale', epsilon=0.1, degree=0)
model.fit(X_train, y_train)
model.score(X_test, y_test)

-1.5710674481759082

In [23]:
import joblib
joblib.dump(model,"../Trained_model/Weights_Prediction_Banana")

['../Trained_model/Weights_Prediction_Banana']